sudo: required
services:
  - docker

before_install:
  - docker build -t gericenit/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run gericenit/react-test npm test -- --coverage

after_success:
  - docker build -t gericenit/multi-client ./client
  - docker build -t gericenit/multi-nginx ./nginx
  - docker build -t gericenit/multi-server ./server
  - docker build -t gericenit/multi-worker ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push gericenit/multi-client
  - docker push gericenit/multi-nginx
  - docker push gericenit/multi-server
  - docker push gericenit/multi-worker
